export const theme = {
  colors: {
    bg: "#ffffff",
    bgSecondary: "#f5f5f5",
    bgTertiary: "#e5e5e5",
    text: "#0a0a0a",
    textSecondary: "#525252",
    textMuted: "#a3a3a3",
    border: "#e5e5e5",
    accent: "#0a0a0a",
    accentText: "#ffffff",
    error: "#dc2626",
    errorBg: "#fef2f2",
    warning: "#ca8a04",
    warningBg: "#fefce8",
    success: "#16a34a",
    overlay: "rgba(0,0,0,0.4)",
    inputBg: "#f5f5f5",
    bubbleOwn: "#0a0a0a",
    bubbleOwnText: "#ffffff",
    bubbleOther: "#f5f5f5",
    bubbleOtherText: "#0a0a0a",
    pinKey: "#f5f5f5",
    pinDotFilled: "#0a0a0a",
    pinDotEmpty: "#d4d4d4",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    full: 9999,
  },
  font: {
    size: {
      xs: 11,
      sm: 13,
      md: 16,
      lg: 18,
      xl: 20,
      xxl: 24,
    },
    weight: {
      light: "300" as const,
      normal: "400" as const,
      medium: "500" as const,
      semibold: "600" as const,
      bold: "bold" as const,
    },
  },
  statusBar: "dark" as const,
} as const;

export type Theme = typeof theme;
